id: P000465
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W21588
  title: གསོ་རིག་གཅེས་བཏུས་རིན་ཆེན་ཕྲེང་བ
  author: ''
  volumes:
    8377f4cc17d44bfa8194922119cd9e56:
      image_group_id: I4198
      title: ''
      volume_number: 1
      total_pages: 786
      base_file: v001.txt
